# Generated by Django 4.2.7 on 2025-10-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_producto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Persona",
        ),
    ]
