# Generated by Django 4.2.7 on 2025-10-26 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_alter_producto_categoria_alter_producto_creado_por_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("editar", "Editar"),
                            ("eliminar", "Eliminar"),
                            ("activar", "Activar"),
                            ("desactivar", "Desactivar"),
                            ("cambiar_rol", "Cambiar Rol"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("producto", "Producto"),
                            ("usuario", "Usuario"),
                            ("pedido", "Pedido"),
                            ("notificacion", "Notificación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objeto_id", models.IntegerField()),
                ("objeto_repr", models.CharField(max_length=500)),
                ("detalles", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
                    ),
                    models.Index(
                        fields=["modulo", "-timestamp"],
                        name="audit_logs_modulo_ed3939_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-timestamp"],
                        name="audit_logs_usuario_5354f3_idx",
                    ),
                ],
            },
        ),
    ]
