# Generated by Django 4.2.7 on 2025-10-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
