# Generated by Django 4.2.7 on 2025-10-26 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_alter_producto_imagen_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("jti", models.CharField(db_index=True, max_length=36, unique=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revocado", models.BooleanField(default=False)),
                ("revocado_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refresh_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="refresh_tok_usuario_21e2fa_idx",
                    ),
                    models.Index(
                        fields=["token_hash"], name="refresh_tok_token_h_2fa7c6_idx"
                    ),
                    models.Index(fields=["jti"], name="refresh_tok_jti_121d6d_idx"),
                    models.Index(
                        fields=["expires_at"], name="refresh_tok_expires_a128d9_idx"
                    ),
                ],
            },
        ),
    ]
