# Generated by Django 4.2.7 on 2025-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_refreshtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[("login", "Login"), ("register", "Register")],
                        default="login",
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "login_attempts",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="login_attem_ip_addr_340a7c_idx",
                    ),
                    models.Index(
                        fields=["username", "timestamp"],
                        name="login_attem_usernam_ece61f_idx",
                    ),
                ],
            },
        ),
    ]
