# Generated by Django 4.2.7 on 2025-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_loginattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="jti",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
