# Generated by Django 4.2.7 on 2025-11-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_refreshtoken_jti"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descuento",
            field=models.IntegerField(
                default=0, help_text="Porcentaje de descuento (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="en_carrusel",
            field=models.BooleanField(
                default=False, help_text="Mostrar en carrusel principal"
            ),
        ),
    ]
