# Generated by Django 4.2.7 on 2025-11-06 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0011_producto_descuento_producto_en_carrusel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(db_index=True, unique=True)),
                (
                    "blacklisted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "razon",
                    models.CharField(
                        choices=[
                            ("logout", "Logout"),
                            ("revoked", "Revocado"),
                            ("expired", "Expirado"),
                            ("security", "Razón de Seguridad"),
                        ],
                        default="logout",
                        max_length=50,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Blacklist",
                "verbose_name_plural": "Tokens Blacklist",
                "db_table": "token_blacklist",
                "ordering": ["-blacklisted_at"],
                "indexes": [
                    models.Index(fields=["token"], name="token_black_token_6a50c6_idx"),
                    models.Index(
                        fields=["usuario", "blacklisted_at"],
                        name="token_black_usuario_bfae6c_idx",
                    ),
                    models.Index(
                        fields=["blacklisted_at"], name="token_black_blackli_ad3082_idx"
                    ),
                ],
            },
        ),
    ]
