# Generated by Django 4.2.7 on 2025-11-07 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0012_tokenblacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del carrito"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización del carrito"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario propietario del carrito",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
                "db_table": "carts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Cantidad del producto"
                    ),
                ),
                (
                    "price_at_addition",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto al momento de agregar",
                        max_digits=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de agregación al carrito"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización del item"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Carrito al que pertenece este item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto en el carrito",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item del Carrito",
                "verbose_name_plural": "Items del Carrito",
                "db_table": "cart_items",
                "ordering": ["-created_at"],
                "unique_together": {("cart", "product")},
            },
        ),
    ]
