# Generated by Django 4.2.7 on 2025-11-08 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0013_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Agregar producto"),
                            ("update", "Actualizar cantidad"),
                            ("remove", "Eliminar producto"),
                            ("clear", "Vaciar carrito"),
                        ],
                        help_text="Tipo de acción realizada",
                        max_length=10,
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(
                        blank=True, help_text="ID del producto (si aplica)", null=True
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del producto (snapshot)",
                        max_length=255,
                    ),
                ),
                (
                    "quantity_before",
                    models.IntegerField(
                        blank=True, help_text="Cantidad antes de la acción", null=True
                    ),
                ),
                (
                    "quantity_after",
                    models.IntegerField(
                        blank=True, help_text="Cantidad después de la acción", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio del producto en el momento",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP del cliente", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User-Agent del navegador"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de la acción"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que realizó la acción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría del Carrito",
                "verbose_name_plural": "Registros de Auditoría del Carrito",
                "db_table": "cart_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="cart_audit__user_id_a35ac4_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="cart_audit__action_a826f8_idx",
                    ),
                ],
            },
        ),
    ]
