# Generated by Django 4.2.7 on 2025-11-08 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_favorito"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorito",
            name="unique_usuario_producto",
        ),
        migrations.AlterUniqueTogether(
            name="favorito",
            unique_together={("usuario", "producto")},
        ),
    ]
