# Generated by Django 4.2.7 on 2025-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_favorito_unique_usuario_producto_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="cart_items_cart_id_3caa7d_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="cart_items_product_6a1de7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorito",
            index=models.Index(
                fields=["usuario", "-created_at"], name="favoritos_usuario_d7c5bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorito",
            index=models.Index(
                fields=["producto"], name="favoritos_product_a4c7bc_idx"
            ),
        ),
    ]
