# Generated by Django 4.2.7 on 2025-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_cartitem_cart_items_cart_id_3caa7d_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("electrodomesticos", "Electrodomésticos"),
                    ("energia_tecnologia", "Energía y Tecnología"),
                    ("herramientas", "Herramientas"),
                    ("hogar_entretenimiento", "Hogar y Entretenimiento"),
                    ("otros", "Otros Artículos"),
                ],
                default="otros",
                max_length=50,
            ),
        ),
    ]
