# Generated by Django 4.2.7 on 2025-11-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_stock_system"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="producto",
            new_name="productos_stock_2e1108_idx",
            old_name="productos_stock_idx",
        ),
        migrations.RenameIndex(
            model_name="producto",
            new_name="productos_stock_r_a1448d_idx",
            old_name="productos_stock_reservado_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_usuario_bec55e_idx",
            old_name="stock_reservations_usuario_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_product_991f92_idx",
            old_name="stock_reservations_producto_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_status_da6fe9_idx",
            old_name="stock_reservations_status_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="stock_reser_expires_fdd22d_idx",
            old_name="stock_reservations_expires_idx",
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(
                default=0, help_text="Stock disponible (total - reservado - vendido)"
            ),
        ),
    ]
