# Generated by Django 4.2.7 on 2025-11-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_cart_prod_idx",
        ),
        migrations.RemoveIndex(
            model_name="favorito",
            name="favorito_user_prod_idx",
        ),
        migrations.RemoveIndex(
            model_name="favorito",
            name="favorito_producto_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="producto_carousel_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="producto_active_cat_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="producto_stock_idx",
        ),
    ]
