# Generated by Django 4.2.7 on 2025-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_cartitem_cartitem_cart_prod_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Agregar producto"),
                    ("update", "Actualizar cantidad"),
                    ("remove", "Eliminar producto"),
                    ("clear", "Vaciar carrito"),
                    ("bulk_update", "Actualización masiva"),
                ],
                help_text="Tipo de acción realizada",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="user_agent",
            field=models.TextField(
                blank=True, default="", help_text="User-Agent del navegador"
            ),
        ),
    ]
