# Generated by Django 4.2.7 on 2025-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_cartauditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreservation",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="User-Agent del navegador", null=True
            ),
        ),
    ]
