# Generated by Django 4.2.7 on 2025-11-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_add_performance_indexes_v2"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="producto",
            name="api_producto_en_carrusel_activo_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="api_producto_categoria_activo_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="api_producto_created_at_desc_idx",
        ),
        migrations.AlterField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("electrodomesticos", "Electrodomésticos"),
                    ("energia_tecnologia", "Energía y Tecnología"),
                    ("herramientas", "Herramientas"),
                    ("hogar_entretenimiento", "Hogar y Entretenimiento"),
                    ("otros", "Otros Artículos"),
                ],
                default="otros",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="en_carrusel",
            field=models.BooleanField(
                default=False, help_text="Mostrar en carrusel principal"
            ),
        ),
    ]
