# Generated by Django 4.2.7 on 2025-11-25 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0028_add_visibility_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verificado", models.BooleanField(default=False)),
                ("verificado_at", models.DateTimeField(blank=True, null=True)),
                ("intentos_fallidos", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("ultimo_reenvio", models.DateTimeField(blank=True, null=True)),
                ("contador_reenvios", models.IntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="email_verif_usuario_3982b5_idx",
                    ),
                    models.Index(
                        fields=["codigo", "expires_at"],
                        name="email_verif_codigo_7f1514_idx",
                    ),
                ],
            },
        ),
    ]
