# Generated by Django 4.2.7 on 2025-11-25 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0031_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordRecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("verificado", models.BooleanField(default=False)),
                ("verificado_at", models.DateTimeField(blank=True, null=True)),
                ("intentos_fallidos", models.IntegerField(default=0)),
                ("contador_reenvios", models.IntegerField(default=0)),
                ("ultimo_reenvio", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "verificado"],
                        name="api_passwor_usuario_e910e4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="api_passwor_expires_67838b_idx"
                    ),
                ],
            },
        ),
    ]
