# Generated by Django 4.2.7 on 2025-11-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_passwordrecoverycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="attempt_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                    ("forgot_password", "Forgot Password"),
                ],
                default="login",
                max_length=20,
            ),
        ),
    ]
