"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

# Frontend URL para enlaces en emails
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_celery_beat',  # Celery Beat para tareas programadas
    'django_celery_results',  # Almacenar resultados de tareas
    'api',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',  # Compresión GZIP
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.JWTAuthenticationMiddleware',  # Autenticación JWT
    'api.middleware.TokenBlacklistMiddleware',  # Validar tokens en blacklist
]

# GZIP Configuration
GZIP_LEVEL = 6  # Balance entre velocidad y compresión (1-9)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'electro_isla'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,  # Pool de conexiones (10 minutos)
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ═══════════════════════════════════════════════════════════════════════════════
# 📧 EMAIL CONFIGURATION (Gmail)
# ═══════════════════════════════════════════════════════════════════════════════

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # Your Gmail address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # App password
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "https://electro-isla.com",  # Producción
]

CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'https://electro-isla.com',  # Producción
]

CSRF_COOKIE_SECURE = False  # True en producción (HTTPS)
CSRF_COOKIE_HTTPONLY = False  # Necesario para leer desde JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'  # Protección contra CSRF
CSRF_COOKIE_AGE = 31449600  # 1 año (en segundos)

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.JWTAuthentication',  # Nuestra autenticación JWT personalizada
        'rest_framework.authentication.TokenAuthentication',  # Fallback para compatibilidad
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    # 🚦 Rate Limiting - Throttles por scope (Producción Realista)
    # NO activamos throttles globales para no afectar endpoints públicos cacheados
    'DEFAULT_THROTTLE_CLASSES': [],
    
    # 🎯 Tasas de throttle por scope (configurable vía env vars en producción)
    'DEFAULT_THROTTLE_RATES': {
        # 🔐 Autenticación (anónimos) - Previene fuerza bruta
        'anon_auth': os.getenv('THROTTLE_ANON_AUTH', '5/minute'),
        
        # 🛒 Carrito - Escritura masiva (bulk-update)
        'cart_write': os.getenv('THROTTLE_CART_WRITE', '30/minute'),
        
        # 💳 Checkout - Operación crítica
        'checkout': os.getenv('THROTTLE_CHECKOUT', '5/hour'),
        
        # 🧑‍💼 Admin - Panel administrativo
        'admin': os.getenv('THROTTLE_ADMIN', '2000/hour'),
        
        # 👥 Usuario - Endpoints logueados
        'user': os.getenv('THROTTLE_USER', '5000/hour'),
        
        # 🌍 Anónimo - Endpoints públicos
        'anon': os.getenv('THROTTLE_ANON', '1000/hour'),
    },
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'auth_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'auth.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'auth': {
            'handlers': ['console', 'auth_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Security Headers
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# HTTPS Settings (desarrollo: False, producción: True)
SECURE_SSL_REDIRECT = False  # True en producción
SESSION_COOKIE_SECURE = False  # True en producción
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000  # 1 año en producción
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Cache Configuration
# Redis para datos públicos (catálogo, categorías, etc.)
# Memoria local para sesiones activas
CACHES = {
    # Redis para datos públicos (catálogo, categorías, etc.)
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        }
    },
    # Memoria local para sesiones activas
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'session-cache',
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'

# File Upload Settings - Permitir imágenes base64 grandes
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB en bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB en bytes

# ═══════════════════════════════════════════════════════════════════════════════
# 🚀 CELERY CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

# ✅ CELERY REACTIVADO - Versión 5.5.3 (bug solucionado)
# Ahora usa broker de Redis para tareas asincrónicas
# CELERY_ALWAYS_EAGER deshabilitado para usar worker real

# Broker (donde se almacenan las tareas pendientes)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')

# Result backend (donde se guardan los resultados de las tareas)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')

# Serialización de tareas
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone para tareas programadas
CELERY_TIMEZONE = 'America/Santo_Domingo'

# Configuración de Beat (tareas programadas)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Configuración de resultados
CELERY_RESULT_EXPIRES = 3600  # Los resultados expiran después de 1 hora

# Logging de Celery
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos (hard limit)
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutos (soft limit)

# ✅ CONFIGURACIÓN PARA WINDOWS - POOL SOLO
# Forzar que use 'solo' pool en lugar de 'prefork' (que no funciona en Windows)
CELERY_WORKER_POOL = 'solo'
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_DISABLE_RATE_LIMITS = True
